"""Shared interpretation guidance for CLI and connected-assistant previews."""

INTENT_GUIDANCE = (
    "Distinguish actual research targets from reference entities, comparison baselines, and exclusions. "
    "A named company is not automatically a target. For 'competitors of A', 'A와 경쟁하는 업체', "
    "or 'A와 경쟁사인 업체', A is the reference company; research its competitors and exclude A's own "
    "products and prices unless the user explicitly asks to include A. For 'compare A and its competitors', "
    "include both. Apply the same distinction to brands, products, suppliers, and all industries. "
    "Keep each company or source paired with its own requested products and URLs. A product list "
    "qualified by one company must not become a global filter for other companies. Preserve explicitly "
    "selected product URLs even when their products differ across companies; explain the difference "
    "instead of silently replacing or excluding them. "
    "State the target scope and reference/excluded entities clearly in summary and note before suggesting "
    "candidate links. Reference-company pages may support competitor identification but must not be "
    "proposed as collection targets in a competitors-only request. Express an excluded reference "
    "entity as a brand or seller not_equals condition according to its actual role; a rental "
    "operator, for example, is a seller/provider, not a vehicle brand. Do not encode company roles as "
    "literal include_terms or exclude_terms: a competitor page can mention the reference company. "
    "A group such as 'A or its competitors' is a research population, not a single manufacturer, "
    "brand, or seller value. Do not put OR choices, competitor relationships, or market scope inside "
    "one product condition. Keep them in topic, summary, and note. When the user explicitly includes "
    "A in a comparison, seek at least one evidenced candidate for A as well as a competitor, if "
    "public search evidence supports both; never invent a source to fill a slot. "
    "Preserve the original request. If the relationship is genuinely ambiguous, explain the alternatives "
    "in note and leave candidates empty for clarification; do not silently broaden the scope. "
    "Derive industry and product from the request's explicit meaning rather than unrelated saved workspace "
    "defaults. Leave an unspecified geographic market empty; a product or industry name is not a market. "
    "When market is absent, do not search for or suggest sales sources yet; ask which geographic "
    "market the user means and leave candidates empty. Never treat an example country as requested. "
)
